config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  resources :books # set the basic routes for RESTful actions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, :link, presence: true # validation

    before_create {|book| book.title = book.title.split.map(&:capitalize).join(' ')} # Capitalize each word of the book title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.order(:title) # arrange the index alphabetically
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to root_path # redirects to index when deleting a book
  end

  private
    def book_params
      params.require(:book).permit(:title, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with class: "container p-3 mx-auto", model: book do |form| %>
    <div class="mb-3 mx-5">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, class: "form-control" %>
        <% book.errors.full_messages_for(:title).each do |message| %>
            <div class="text-danger mt-1 ml-5"><%= message %></div>
        <% end %>
    </div>

    <div class="mb-3 mx-5">
        <%= form.label :link, class: "form-label" %>
        <%= form.text_area :link, class: "form-control", placeholder: "https://www.linktoresource.com" %>
        <% book.errors.full_messages_for(:link).each do |message| %>
            <div class="text-danger mt-1"><%= message %></div>
        <% end %>
    </div>

    <div class="mx-5 form-options">
        <%= form.submit "Add Book", class: "btn btn-outline-primary" %>
        <%= link_to "Cancel", book, class: "btn btn-outline-danger"  %>
    </div>
<% end %>

app/views/books/edit.html.erb
<nav class="navbar bg-light p-3 mx-auto">
  <div class="container-fluid">
    <div class="d-flex align-items-center brand-name">
      <a href="https://www.flaticon.com/free-icons/library" title="Library icons created by nawicon - Flaticon"><img src="/assets/logo.png" class="logo" alt="Library icons created by nawicon - Flaticon"></a>
      <%= link_to "Linkrary", root_path, class: "navbar-brand mb-0 h1 brand" %>
      <p class="text-muted">Library of digital books </p>
    </div>
  </div>
</nav>

<%= render "form", book: @book %>

app/views/books/index.html.erb
<nav class="navbar bg-light p-3 mx-auto">
  <div class="container-fluid">
    <div class="d-flex align-items-center brand-name">
      <a href="https://www.flaticon.com/free-icons/library" title="Library icons created by nawicon - Flaticon"><img src="/assets/logo.png" class="logo" alt="Library icons created by nawicon - Flaticon"></a>

      <%= link_to "Linkrary", root_path, class: "navbar-brand mb-0 h1 brand" %>

      <p class="text-muted">Library of digital books </p>
      
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      </form>
    </div>

      <%= link_to "Add Book", new_book_path, class: "btn btn-outline-primary" %>
  </div>
</nav>

<div class="container">
    <ul class="list-group">
        <% @books.each do |book| %>
            <li class="book-list">
                <%= link_to book.title, book, class: "list-group-item list-group-item-action"%>
            </li>
        <% end %>
    </ul>
</div>

app/views/books/new.html.erb
<nav class="navbar bg-light p-3 mx-auto">
  <div class="container-fluid">
    <div class="d-flex align-items-center brand-name">
      <a href="https://www.flaticon.com/free-icons/library" title="Library icons created by nawicon - Flaticon"><img src="/assets/logo.png" class="logo" alt="Library icons created by nawicon - Flaticon"></a>
      <%= link_to "Linkrary", root_path, class: "navbar-brand mb-0 h1 brand" %>
      <p class="text-muted">Library of digital books </p>
    </div>
  </div>
</nav>

<%= render "form", book: @book %>

app/views/books/show.html.erb
<nav class="navbar bg-light p-3 mx-auto">
  <div class="container-fluid">
    <div class="d-flex align-items-center brand-name">
      <a href="https://www.flaticon.com/free-icons/library" title="Library icons created by nawicon - Flaticon"><img src="/assets/logo.png" class="logo" alt="Library icons created by nawicon - Flaticon"></a>
      <%= link_to "Linkrary", root_path, class: "navbar-brand mb-0 h1 brand" %>
      <p class="text-muted">Library of digital books </p>
    </div>
  </div>
</nav>

<a href="<%= root_path %>" class="d-block mb-3 px-3 icons"><i class="bi bi-arrow-left-short"></i></i> Back</a>


<div class="px-3"> 
  <div class="d-flex flex-column align-items-center mb-3">
    <p class="display-6 mb-2"><%= @book.title %></p>

    <div class="px-3 options">
      <a href="<%= @book.link %>" target="#" class="icon btn btn-outline-primary" title="Read" ><i class="bi bi-book"></i></a>

      <a href="<%= edit_book_path(@book) %>" class="icon btn btn-outline-secondary" title="Edit"><i class="bi bi-pencil-fill"></i></a>

      <a class=" icon btn btn-outline-danger" data-confirm="Are you sure you want to delete this book?" rel="nofollow" data-method="delete" href="<%= book_path(@book) %>" title="Delete"><i class="bi bi-trash"></i></a>
    </div>
  </div>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Linkrary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" type="image/x-icon" href="/assets/logo.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>